spring:
  application:
    name: job-portal

  #    database configuration
  data:
    jdbc:
      dialect: postgresql
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/job-portal
    username: postgres
    password: admin@123
    driver-class-name: org.postgresql.Driver
logging:
  level:
    web: debug
