spring:
  application:
    name: job-portal

  #    database configuration
  data:
    jdbc:
      dialect: postgresql
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/job-portal
    username: postgres
    password: admin@123
    driver-class-name: org.postgresql.Driver

  #    email configuration settings
  mail:
    host: smtp.gmail.com
    port: 587
    username: osteenomega2@gmail.com
    password: yeyzzrxubrgjljmu
    default-encoding: utf-8
    properties:
      smtp:
        ssl:
          trust: smtp.gmail.com
        writetimeout: 10000
        connectiontimeout: 10000
        timeout: 10000
        auth: true
        starttls.enable: true
        required: true
      mail:
        debug:
          true

  # oauth login configurations
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liNvkpO4HNyIyNZU
            client-secret: e2d84ee8b2482577fffa744ffeda44460fccef39
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: user:email

#      logging configurations
logging:
  level:
    web: debug
    org:
      springframework:
        security: debug





